db:
  postgresql:
    connStr: 'postgres://bibhbgwi:ANb3vUUo213tKtNuYC7V812F8-Zdc0gQ@horton.db.elephantsql.com/bibhbgwi'
  neo4j:
    uri: 'neo4j+s://b169bf9c.databases.neo4j.io'
    user: 'neo4j'
    password: 'dE3ikBb4Z5X9V2lklFTq5FBAHLn_OvY6RH30cxkZQPg'
tests:
  configureDb:
    enabled: false
  dataLoad:
    enabled: true
    threadsMax: 100
  aggregation:
    enabled: true
  patternMatching:
    enabled: true
  simple:
    enabled: false
  traversal:
    enabled: false
  filters:
    patentId: '3858241'
    author: 'Frederick'
    registrationDate: '1975-01-01'
data:
  fake:
    authorsTotal: 10000
    classificationsTotal: 400
  dataset:
    startDate: '1975-01-01 00:00:00'
    endDate: '1999-12-31 00:00:00'
    total: 10000
    filePath: domain/dataset/snap/stanford/cit-Patents.txt
  max: 10000
results:
  basePath: tests/10k/results