db:
  postgresql:
    connStr: ''
  neo4j:
    uri: 'neo4j+s://b169bf9c.databases.neo4j.io'
    user: 'neo4j'
    password: ''
tests:
  configureDb:
    enabled: true
  dataLoad:
    enabled: true
    threadsMax: 100
  traversal:
    enabled: true
    filters:
      patentId: '3858241'
      author: 'Travis'
      registerDate: '1975-01-01'
data:
  fake:
    authorsTotal: 10
    classificationsTotal: 10
    datetimesTotal: 10
  dataset:
    startDate: '1975-01-01 00:00:00'
    endDate: '1999-12-31 00:00:00'
    total: 17
    filePath: domain/dataset/snap/stanford/cit-Patents.txt
  max: 600
results:
  basePath: tests/results